apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
   name: crossplane-ec2
   namespace: default
spec:
   forProvider:
        imageId: ami-052efd3df9dad4825
        instanceType: t2.micro
        region: us-east-2
