apiVersion: cache.aws.crossplane.io/v1alpha1
kind: CacheCluster
spec:
	deletionPolicy: "Delete"
	forProvider:
		cacheNodeType: "cache.t2.micro" 
		numCacheNodes: 3
		region: "us-east-1"
		tags: 
		- key: "Group"
		  value: "Krishna"