apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rdsmysql
spec:
  forProvider:
    region: us-east-1
    dbInstanceClass: db.t3.micro
    masterUsername: masteruser
    allocatedStorage: 20
    engine: mysql
    engineVersion: "8.0"
    skipFinalSnapshotBeforeDeletion: true
    tags:
    - key: Group
      value: Krishna
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: aws-rdsmysql-conn
