apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: votingapp
spec:
  generators:
  - list:
      elements:
      - cluster: arn:aws:eks:us-east-1:376329890665:cluster/krishna-k8s-cluster
        url: 172.20.0.1:443
      - cluster: minikube
        url: https://127.0.0.1:31364
  template:
    metadata:
      name: 'votingapp1'
    spec:
      project: default
      source:
        repoURL: https://github.com/yogeshphilips-partner/Voting-app.git
        targetRevision: HEAD
        path: K8s-deploy/
      destination:
        server: '{{url}}'
        namespace: default
